// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supervisor.proto

package supervisor // import "github.com/juxuny/supervisor"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proxy "github.com/juxuny/supervisor/proxy"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApplyReq struct {
	Config               *DeployConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *ApplyReq) Reset()         { *m = ApplyReq{} }
func (m *ApplyReq) String() string { return proto.CompactTextString(m) }
func (*ApplyReq) ProtoMessage()    {}
func (*ApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{0}
}
func (m *ApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyReq.Unmarshal(m, b)
}
func (m *ApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyReq.Marshal(b, m, deterministic)
}
func (dst *ApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyReq.Merge(dst, src)
}
func (m *ApplyReq) XXX_Size() int {
	return xxx_messageInfo_ApplyReq.Size(m)
}
func (m *ApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyReq proto.InternalMessageInfo

func (m *ApplyReq) GetConfig() *DeployConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type ApplyResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ApplyResp) Reset()         { *m = ApplyResp{} }
func (m *ApplyResp) String() string { return proto.CompactTextString(m) }
func (*ApplyResp) ProtoMessage()    {}
func (*ApplyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{1}
}
func (m *ApplyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResp.Unmarshal(m, b)
}
func (m *ApplyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResp.Marshal(b, m, deterministic)
}
func (dst *ApplyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResp.Merge(dst, src)
}
func (m *ApplyResp) XXX_Size() int {
	return xxx_messageInfo_ApplyResp.Size(m)
}
func (m *ApplyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResp proto.InternalMessageInfo

func (m *ApplyResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ApplyResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeployConfig struct {
	ServicePort          uint32       `protobuf:"varint,1,opt,name=service_port,json=servicePort" json:"service_port,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Image                string       `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Tag                  string       `protobuf:"bytes,4,opt,name=tag" json:"tag,omitempty"`
	Mounts               []*Mount     `protobuf:"bytes,5,rep,name=mounts" json:"mounts,omitempty"`
	EnvData              string       `protobuf:"bytes,6,opt,name=env_data,json=envData" json:"env_data,omitempty"`
	Envs                 []*KeyValue  `protobuf:"bytes,7,rep,name=envs" json:"envs,omitempty"`
	PullRetryTimes       uint32       `protobuf:"varint,8,opt,name=pull_retry_times,json=pullRetryTimes" json:"pull_retry_times,omitempty"`
	Version              uint32       `protobuf:"varint,9,opt,name=version" json:"version,omitempty"`
	HealthCheck          *HealthCheck `protobuf:"bytes,10,opt,name=health_check,json=healthCheck" json:"health_check,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" bson:"-"`
}

func (m *DeployConfig) Reset()         { *m = DeployConfig{} }
func (m *DeployConfig) String() string { return proto.CompactTextString(m) }
func (*DeployConfig) ProtoMessage()    {}
func (*DeployConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{2}
}
func (m *DeployConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployConfig.Unmarshal(m, b)
}
func (m *DeployConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployConfig.Marshal(b, m, deterministic)
}
func (dst *DeployConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployConfig.Merge(dst, src)
}
func (m *DeployConfig) XXX_Size() int {
	return xxx_messageInfo_DeployConfig.Size(m)
}
func (m *DeployConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DeployConfig proto.InternalMessageInfo

func (m *DeployConfig) GetServicePort() uint32 {
	if m != nil {
		return m.ServicePort
	}
	return 0
}

func (m *DeployConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DeployConfig) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *DeployConfig) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *DeployConfig) GetEnvData() string {
	if m != nil {
		return m.EnvData
	}
	return ""
}

func (m *DeployConfig) GetEnvs() []*KeyValue {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *DeployConfig) GetPullRetryTimes() uint32 {
	if m != nil {
		return m.PullRetryTimes
	}
	return 0
}

func (m *DeployConfig) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DeployConfig) GetHealthCheck() *HealthCheck {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

type HealthCheck struct {
	Type                 proxy.HealthCheckType `protobuf:"varint,1,opt,name=type,enum=proxy.HealthCheckType" json:"type,omitempty"`
	Path                 string                `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Port                 uint32                `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-" bson:"-"`
	XXX_unrecognized     []byte                `json:"-" bson:"-"`
	XXX_sizecache        int32                 `json:"-" bson:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{3}
}
func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (dst *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(dst, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func (m *HealthCheck) GetType() proxy.HealthCheckType {
	if m != nil {
		return m.Type
	}
	return proxy.HealthCheckType_TypeDefault
}

func (m *HealthCheck) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HealthCheck) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Mount struct {
	HostPath             string   `protobuf:"bytes,1,opt,name=host_path,json=hostPath" json:"host_path,omitempty"`
	MountPath            string   `protobuf:"bytes,2,opt,name=mount_path,json=mountPath" json:"mount_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{4}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *Mount) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{5}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{6}
}
func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (dst *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(dst, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResp struct {
	Config               []*DeployConfig `protobuf:"bytes,1,rep,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" bson:"-"`
	XXX_unrecognized     []byte          `json:"-" bson:"-"`
	XXX_sizecache        int32           `json:"-" bson:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_e5bfc410812a6804, []int{7}
}
func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (dst *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(dst, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetConfig() []*DeployConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplyReq)(nil), "supervisor.ApplyReq")
	proto.RegisterType((*ApplyResp)(nil), "supervisor.ApplyResp")
	proto.RegisterType((*DeployConfig)(nil), "supervisor.DeployConfig")
	proto.RegisterType((*HealthCheck)(nil), "supervisor.HealthCheck")
	proto.RegisterType((*Mount)(nil), "supervisor.Mount")
	proto.RegisterType((*KeyValue)(nil), "supervisor.KeyValue")
	proto.RegisterType((*GetReq)(nil), "supervisor.GetReq")
	proto.RegisterType((*GetResp)(nil), "supervisor.GetResp")
}

func init() { proto.RegisterFile("supervisor.proto", fileDescriptor_supervisor_e5bfc410812a6804) }

var fileDescriptor_supervisor_e5bfc410812a6804 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x75, 0x3e, 0xc7, 0xa1, 0x4a, 0x96, 0x02, 0x4b, 0x28, 0x28, 0xf8, 0x14, 0x38, 0x24,
	0x25, 0x20, 0x0e, 0xc0, 0x05, 0x52, 0xa9, 0x48, 0x08, 0x29, 0x72, 0x2b, 0x0e, 0x5c, 0xac, 0xad,
	0xbb, 0xd8, 0xa6, 0xb6, 0x77, 0xeb, 0x5d, 0x5b, 0xf5, 0x7f, 0xe2, 0x2f, 0xf1, 0x5f, 0xd0, 0x8e,
	0x1d, 0xe2, 0x02, 0x87, 0x5e, 0xac, 0x99, 0xf7, 0xe6, 0xbd, 0x91, 0x67, 0x66, 0x61, 0xac, 0x0a,
	0xc9, 0xf3, 0x32, 0x56, 0x22, 0x5f, 0xc8, 0x5c, 0x68, 0x41, 0x60, 0x87, 0x4c, 0x27, 0x32, 0x17,
	0xd7, 0xd5, 0x12, 0xbf, 0x35, 0xed, 0xbe, 0x87, 0xc1, 0x07, 0x29, 0x93, 0xca, 0xe3, 0x57, 0xe4,
	0x08, 0x7a, 0x81, 0xc8, 0xbe, 0xc7, 0x21, 0xb5, 0x66, 0xd6, 0xdc, 0x59, 0xd1, 0x45, 0xcb, 0xed,
	0x98, 0xcb, 0x44, 0x54, 0x6b, 0xe4, 0xbd, 0xa6, 0xce, 0x7d, 0x09, 0xc3, 0x46, 0xad, 0x24, 0x21,
	0xd0, 0x09, 0xc4, 0x05, 0x47, 0xf1, 0x5d, 0x0f, 0x63, 0x32, 0x06, 0x3b, 0x55, 0x21, 0xdd, 0x9b,
	0x59, 0xf3, 0xa1, 0x67, 0x42, 0xf7, 0xd7, 0x1e, 0x8c, 0xda, 0x5e, 0xe4, 0x19, 0x8c, 0x94, 0x69,
	0x12, 0x70, 0x5f, 0x8a, 0x5c, 0x37, 0x72, 0xa7, 0xc1, 0x36, 0x22, 0xd7, 0xc6, 0x39, 0x63, 0x29,
	0x6f, 0x6c, 0x30, 0x26, 0x07, 0xd0, 0x8d, 0x53, 0x16, 0x72, 0x6a, 0x23, 0x58, 0x27, 0xa6, 0x9f,
	0x66, 0x21, 0xed, 0xd4, 0xfd, 0x34, 0x0b, 0xc9, 0x73, 0xe8, 0xa5, 0xa2, 0xc8, 0xb4, 0xa2, 0xdd,
	0x99, 0x3d, 0x77, 0x56, 0x93, 0xf6, 0x4f, 0x7d, 0x31, 0x8c, 0xd7, 0x14, 0x90, 0x47, 0x30, 0xe0,
	0x59, 0xe9, 0x5f, 0x30, 0xcd, 0x68, 0x0f, 0x1d, 0xfa, 0x3c, 0x2b, 0x8f, 0x99, 0x66, 0x64, 0x0e,
	0x1d, 0x9e, 0x95, 0x8a, 0xf6, 0xd1, 0xe3, 0xa0, 0xed, 0xf1, 0x99, 0x57, 0x5f, 0x59, 0x52, 0x70,
	0x0f, 0x2b, 0xc8, 0x1c, 0xc6, 0xb2, 0x48, 0x12, 0x3f, 0xe7, 0x3a, 0xaf, 0x7c, 0x1d, 0xa7, 0x5c,
	0xd1, 0x01, 0xfe, 0xd2, 0xbe, 0xc1, 0x3d, 0x03, 0x9f, 0x19, 0x94, 0x50, 0xe8, 0x97, 0x3c, 0x57,
	0xb1, 0xc8, 0xe8, 0x10, 0x0b, 0xb6, 0x29, 0x79, 0x0b, 0xa3, 0x88, 0xb3, 0x44, 0x47, 0x7e, 0x10,
	0xf1, 0xe0, 0x92, 0x02, 0xae, 0xe3, 0x61, 0xbb, 0xeb, 0x27, 0xe4, 0xd7, 0x86, 0xf6, 0x9c, 0x68,
	0x97, 0xb8, 0x0c, 0x9c, 0x16, 0x47, 0x5e, 0x40, 0x47, 0x57, 0xb2, 0x5e, 0xca, 0xfe, 0xea, 0xc1,
	0xa2, 0xde, 0x7d, 0xab, 0xe2, 0xac, 0x92, 0xdc, 0xc3, 0x1a, 0x33, 0x66, 0xc9, 0x74, 0xb4, 0x1d,
	0xb3, 0x89, 0x11, 0x33, 0x5b, 0xb1, 0xeb, 0xa5, 0x9a, 0xd8, 0x5d, 0x43, 0x17, 0x07, 0x47, 0x1e,
	0xc3, 0x30, 0x12, 0x4a, 0xfb, 0xa8, 0xb2, 0x50, 0x35, 0x30, 0xc0, 0xc6, 0x28, 0x9f, 0x00, 0xe0,
	0x5c, 0xfd, 0x96, 0xe7, 0x10, 0x11, 0x43, 0xbb, 0x2b, 0x18, 0x6c, 0x27, 0x67, 0xb6, 0x76, 0xc9,
	0xab, 0xc6, 0xc1, 0x84, 0x66, 0xbb, 0xa5, 0xa1, 0x1a, 0x5d, 0x9d, 0xb8, 0x87, 0xd0, 0x3b, 0xe1,
	0xda, 0x9c, 0xea, 0xf6, 0x22, 0xac, 0xdd, 0x45, 0xb8, 0xef, 0xa0, 0x8f, 0xac, 0x92, 0x37, 0x2e,
	0xd9, 0xbe, 0xcd, 0x25, 0xaf, 0x7e, 0x5a, 0x00, 0xa7, 0x7f, 0x6a, 0xc8, 0x6b, 0x70, 0x36, 0x66,
	0x52, 0xa7, 0x9a, 0xe9, 0x42, 0x91, 0x71, 0x33, 0xb7, 0x3a, 0xf5, 0xf8, 0xd5, 0x74, 0xf2, 0x17,
	0xa2, 0xa4, 0x7b, 0x87, 0xbc, 0x81, 0x2e, 0x3e, 0x07, 0x72, 0xe3, 0x40, 0xb6, 0xef, 0x6b, 0x7a,
	0xff, 0x3f, 0x28, 0xea, 0x8e, 0xc0, 0x3e, 0xe1, 0x9a, 0x90, 0x36, 0x5f, 0xff, 0xe8, 0xf4, 0xde,
	0x3f, 0x98, 0x51, 0x7c, 0x7c, 0xfa, 0xed, 0x30, 0x8c, 0x75, 0x54, 0x9c, 0x2f, 0x02, 0x91, 0x2e,
	0x7f, 0x14, 0xd7, 0x45, 0x56, 0x2d, 0x77, 0x95, 0xe7, 0x3d, 0x7c, 0xdd, 0xaf, 0x7e, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x68, 0xec, 0xc1, 0x02, 0x10, 0x04, 0x00, 0x00,
}
