version: '3.4'

services:
  supervisord:
    environment:
      HOST_PWD: ${PWD}
#    image: juxuny/supervisor:srv-v0.0.2
    build:
      context: ../
      dockerfile: supervisord.dockerfile
    restart: always
    volumes:
      - ../cert:/app/cert
      - ../tmp:/app/tmp
      - ../config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "50060:50060"
