// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supervisor.proto

package supervisor // import "github.com/juxuny/supervisor"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/juxuny/supervisor/proxy"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApplyReq struct {
	Config               *DeployConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *ApplyReq) Reset()         { *m = ApplyReq{} }
func (m *ApplyReq) String() string { return proto.CompactTextString(m) }
func (*ApplyReq) ProtoMessage()    {}
func (*ApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_253dbbf9b041dda7, []int{0}
}
func (m *ApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyReq.Unmarshal(m, b)
}
func (m *ApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyReq.Marshal(b, m, deterministic)
}
func (dst *ApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyReq.Merge(dst, src)
}
func (m *ApplyReq) XXX_Size() int {
	return xxx_messageInfo_ApplyReq.Size(m)
}
func (m *ApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyReq proto.InternalMessageInfo

func (m *ApplyReq) GetConfig() *DeployConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type ApplyResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ApplyResp) Reset()         { *m = ApplyResp{} }
func (m *ApplyResp) String() string { return proto.CompactTextString(m) }
func (*ApplyResp) ProtoMessage()    {}
func (*ApplyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_253dbbf9b041dda7, []int{1}
}
func (m *ApplyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResp.Unmarshal(m, b)
}
func (m *ApplyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResp.Marshal(b, m, deterministic)
}
func (dst *ApplyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResp.Merge(dst, src)
}
func (m *ApplyResp) XXX_Size() int {
	return xxx_messageInfo_ApplyResp.Size(m)
}
func (m *ApplyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResp proto.InternalMessageInfo

func (m *ApplyResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ApplyResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeployConfig struct {
	ServicePort          uint32      `protobuf:"varint,1,opt,name=service_port,json=servicePort" json:"service_port,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Image                string      `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Tag                  string      `protobuf:"bytes,4,opt,name=tag" json:"tag,omitempty"`
	Mounts               []*Mount    `protobuf:"bytes,5,rep,name=mounts" json:"mounts,omitempty"`
	EnvData              string      `protobuf:"bytes,6,opt,name=env_data,json=envData" json:"env_data,omitempty"`
	Envs                 []*KeyValue `protobuf:"bytes,7,rep,name=envs" json:"envs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *DeployConfig) Reset()         { *m = DeployConfig{} }
func (m *DeployConfig) String() string { return proto.CompactTextString(m) }
func (*DeployConfig) ProtoMessage()    {}
func (*DeployConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_253dbbf9b041dda7, []int{2}
}
func (m *DeployConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployConfig.Unmarshal(m, b)
}
func (m *DeployConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployConfig.Marshal(b, m, deterministic)
}
func (dst *DeployConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployConfig.Merge(dst, src)
}
func (m *DeployConfig) XXX_Size() int {
	return xxx_messageInfo_DeployConfig.Size(m)
}
func (m *DeployConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DeployConfig proto.InternalMessageInfo

func (m *DeployConfig) GetServicePort() uint32 {
	if m != nil {
		return m.ServicePort
	}
	return 0
}

func (m *DeployConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DeployConfig) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *DeployConfig) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *DeployConfig) GetEnvData() string {
	if m != nil {
		return m.EnvData
	}
	return ""
}

func (m *DeployConfig) GetEnvs() []*KeyValue {
	if m != nil {
		return m.Envs
	}
	return nil
}

type Mount struct {
	HostPath             string   `protobuf:"bytes,1,opt,name=host_path,json=hostPath" json:"host_path,omitempty"`
	MountPath            string   `protobuf:"bytes,2,opt,name=mount_path,json=mountPath" json:"mount_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_253dbbf9b041dda7, []int{3}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *Mount) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Values               string   `protobuf:"bytes,2,opt,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_253dbbf9b041dda7, []int{4}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

func init() {
	proto.RegisterType((*ApplyReq)(nil), "supervisor.ApplyReq")
	proto.RegisterType((*ApplyResp)(nil), "supervisor.ApplyResp")
	proto.RegisterType((*DeployConfig)(nil), "supervisor.DeployConfig")
	proto.RegisterType((*Mount)(nil), "supervisor.Mount")
	proto.RegisterType((*KeyValue)(nil), "supervisor.KeyValue")
}

func init() { proto.RegisterFile("supervisor.proto", fileDescriptor_supervisor_253dbbf9b041dda7) }

var fileDescriptor_supervisor_253dbbf9b041dda7 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x09, 0xbb, 0x49, 0x93, 0x49, 0x91, 0x76, 0x47, 0x05, 0x99, 0xe5, 0x8f, 0x96, 0x9c,
	0xc2, 0x25, 0x0b, 0x4b, 0xc5, 0x89, 0x0b, 0xb4, 0x37, 0x84, 0xb4, 0x72, 0x25, 0x0e, 0x5c, 0x56,
	0x6e, 0x6a, 0x92, 0xc0, 0x26, 0x76, 0x63, 0x27, 0x6a, 0x78, 0x57, 0xde, 0x05, 0xd9, 0x71, 0x69,
	0x40, 0xbd, 0x44, 0x33, 0xdf, 0x37, 0xf3, 0x9b, 0x8c, 0xc6, 0xb0, 0x50, 0x9d, 0xe4, 0x6d, 0x5f,
	0x29, 0xd1, 0x66, 0xb2, 0x15, 0x5a, 0x20, 0xdc, 0x29, 0xab, 0xa5, 0x6c, 0xc5, 0xcd, 0xb0, 0xb1,
	0xdf, 0xd1, 0x4e, 0x3e, 0x40, 0xf8, 0x51, 0xca, 0xc3, 0x40, 0xf9, 0x35, 0xbe, 0x81, 0x20, 0x17,
	0xcd, 0xf7, 0xaa, 0x20, 0xde, 0xda, 0x4b, 0xe3, 0x2d, 0xc9, 0x26, 0xb4, 0x73, 0x2e, 0x0f, 0x62,
	0x38, 0xb3, 0x3e, 0x75, 0x75, 0xc9, 0x5b, 0x88, 0x5c, 0xb7, 0x92, 0x88, 0x30, 0xcf, 0xc5, 0x15,
	0xb7, 0xcd, 0x8f, 0xa8, 0x8d, 0x71, 0x01, 0xb3, 0x5a, 0x15, 0xe4, 0xe1, 0xda, 0x4b, 0x23, 0x6a,
	0xc2, 0xe4, 0xb7, 0x07, 0xc7, 0x53, 0x16, 0xbe, 0x82, 0x63, 0x65, 0x86, 0xe4, 0x7c, 0x2f, 0x45,
	0xab, 0x5d, 0x7b, 0xec, 0xb4, 0x9d, 0x68, 0xb5, 0x21, 0x37, 0xac, 0xe6, 0x0e, 0x63, 0x63, 0x3c,
	0x01, 0xbf, 0xaa, 0x59, 0xc1, 0xc9, 0xcc, 0x8a, 0x63, 0x62, 0xe6, 0x69, 0x56, 0x90, 0xf9, 0x38,
	0x4f, 0xb3, 0x02, 0x5f, 0x43, 0x50, 0x8b, 0xae, 0xd1, 0x8a, 0xf8, 0xeb, 0x59, 0x1a, 0x6f, 0x97,
	0xd3, 0xa5, 0xbe, 0x18, 0x87, 0xba, 0x02, 0x7c, 0x0a, 0x21, 0x6f, 0xfa, 0xfd, 0x15, 0xd3, 0x8c,
	0x04, 0x96, 0x70, 0xc4, 0x9b, 0xfe, 0x9c, 0x69, 0x86, 0x29, 0xcc, 0x79, 0xd3, 0x2b, 0x72, 0x64,
	0x19, 0x27, 0x53, 0xc6, 0x67, 0x3e, 0x7c, 0x65, 0x87, 0x8e, 0x53, 0x5b, 0x91, 0x9c, 0x81, 0x6f,
	0xa9, 0xf8, 0x0c, 0xa2, 0x52, 0x28, 0xbd, 0x97, 0x4c, 0x97, 0x76, 0xa9, 0x88, 0x86, 0x46, 0xd8,
	0x31, 0x5d, 0xe2, 0x0b, 0x00, 0x3b, 0x74, 0x74, 0xc7, 0xbd, 0x22, 0xab, 0x18, 0x3b, 0x39, 0x85,
	0xf0, 0x16, 0x6b, 0x56, 0xfa, 0xc9, 0x07, 0x47, 0x30, 0x21, 0x3e, 0x81, 0xa0, 0x37, 0x96, 0x72,
	0x8d, 0x2e, 0xdb, 0xfe, 0x02, 0xb8, 0xf8, 0xfb, 0x5f, 0x78, 0x0a, 0xf1, 0xce, 0x1c, 0xfa, 0x42,
	0x33, 0xdd, 0x29, 0x5c, 0x64, 0xe3, 0xd9, 0xc7, 0x94, 0xf2, 0xeb, 0xd5, 0xf2, 0x3f, 0x45, 0xc9,
	0xe4, 0x01, 0xbe, 0x07, 0xdf, 0x5e, 0x14, 0xff, 0xd9, 0xf1, 0xf6, 0x89, 0xac, 0x1e, 0xdf, 0xa3,
	0x9a, 0xbe, 0x4f, 0x2f, 0xbf, 0x3d, 0x2f, 0x2a, 0x5d, 0x76, 0x97, 0x59, 0x2e, 0xea, 0xcd, 0x8f,
	0xee, 0xa6, 0x6b, 0x86, 0xcd, 0x5d, 0xed, 0x65, 0x60, 0x9f, 0xdb, 0xbb, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0x2b, 0xf9, 0x40, 0xa1, 0x02, 0x00, 0x00,
}
